/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
/**
 *
 * @author joseg
 */
public class InterfazVentanaPrincipal extends javax.swing.JFrame {

    private Agenda agenda; //Creamos la agenda
    private javax.swing.JTextField TextoBusqueda;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JLabel EtiquetaTotalContactos;
            
        /**
     * Creates new form InterfazAgenda
     */
    public InterfazVentanaPrincipal() {
        initComponents();
       
        agenda = new Agenda();//Inicializar la agenda correctamente
       
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextoNombre = new javax.swing.JTextField();
        BotonGuardarContacto = new javax.swing.JButton();
        Listado = new javax.swing.JScrollPane();
        ListaContactos = new javax.swing.JList<>();
        TextoApellido = new javax.swing.JTextField();
        TextoTelefono = new javax.swing.JTextField();
        TextoGrupo = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellidos = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Grupo = new javax.swing.JLabel();
        BotonEliminarContacto = new javax.swing.JButton();
        TextoBusqueda = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        EtiquetaTotalContactos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Contactos");

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextoNombre.setForeground(java.awt.Color.lightGray);
        TextoNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoNombre.setText("Ingrese su nombre");
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 200, 25));

        BotonGuardarContacto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonGuardarContacto.setText("Guardar Contacto");
        BotonGuardarContacto.setAlignmentY(0.0F);
        BotonGuardarContacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGuardarContacto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonGuardarContacto.setMargin(new java.awt.Insets(2, 14, 2, 14));
        BotonGuardarContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGuardarContactoMouseClicked(evt);
            }
        });
        BotonGuardarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarContactoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonGuardarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 200, 30));

        ListaContactos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Listado.setViewportView(ListaContactos);

        jPanel1.add(Listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 350, 70));

        TextoApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextoApellido.setForeground(java.awt.Color.lightGray);
        TextoApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoApellido.setText("Ingrese su apellido");
        TextoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(TextoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 200, 25));

        TextoTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextoTelefono.setForeground(java.awt.Color.lightGray);
        TextoTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoTelefono.setText("Ingrese nº teléfono");
        TextoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(TextoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 200, 25));

        TextoGrupo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextoGrupo.setForeground(java.awt.Color.lightGray);
        TextoGrupo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoGrupo.setText("(opcional)");
        TextoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoGrupoActionPerformed(evt);
            }
        });
        jPanel1.add(TextoGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, 25));

        TextoCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextoCorreo.setForeground(java.awt.Color.lightGray);
        TextoCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoCorreo.setText("(opcional)");
        TextoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(TextoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 200, 25));

        Correo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Correo.setText("Correo :");
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 25));

        Nombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Nombre.setText("Nombre :");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 25));

        Apellidos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Apellidos.setText("Apellidos :");
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 25));

        Telefono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Telefono.setText("Teléfono :");
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 25));

        Grupo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Grupo.setText("Grupo :");
        jPanel1.add(Grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 25));

        BotonEliminarContacto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonEliminarContacto.setText("Eliminar Contacto");
        BotonEliminarContacto.setAlignmentY(0.0F);
        BotonEliminarContacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEliminarContacto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonEliminarContacto.setMargin(new java.awt.Insets(2, 14, 2, 14));
        BotonEliminarContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarContactoMouseClicked(evt);
            }
        });
        BotonEliminarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarContactoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 200, 30));

        TextoBusqueda.setToolTipText("Buscar por nombre o teléfono");
        jPanel1.add(TextoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 200, 25));

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarContactos();
            }
        });
        jPanel1.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 80, 25));

        EtiquetaTotalContactos.setText("Total contactos: 0");
        jPanel1.add(EtiquetaTotalContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGuardarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarContactoActionPerformed

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed

    private void TextoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoApellidoActionPerformed

    private void TextoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoTelefonoActionPerformed

    private void TextoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoGrupoActionPerformed

    private void TextoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCorreoActionPerformed

    private void BotonGuardarContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarContactoMouseClicked
        // Obtener los datos escritos por el usuario
        String nombre = TextoNombre.getText();//Obtiene el texto que el usuario escribió en el campo "Nombre"
        String apellidos = TextoApellido.getText();
        String telefono = TextoTelefono.getText();
        String grupo = TextoGrupo.getText();
        String correo = TextoCorreo.getText();
        //crear un nuevo contacto con estos datos obtenidos, creamos un objeto contacto con los datos ingresados
        Contacto nuevoContacto = new Contacto(nombre, apellidos, telefono, grupo, correo);
        //Agregar el contacto a la agenda
        agenda.agregarContacto(nuevoContacto);
        
        //Limpiar los campos después de guardar para que se pueda crear otro contacto.
        TextoNombre.setText("");
        TextoApellido.setText("");
        TextoTelefono.setText("");
        TextoGrupo.setText("");
        TextoCorreo.setText("");

        actualizarTotalContactos();
    }//GEN-LAST:event_BotonGuardarContactoMouseClicked

    private void BotonEliminarContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarContactoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarContactoMouseClicked

    private void BotonEliminarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarContactoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazVentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JButton BotonEliminarContacto;
    private javax.swing.JButton BotonGuardarContacto;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel EtiquetaTotalContactos;
    private javax.swing.JLabel Grupo;
    private javax.swing.JList<String> ListaContactos;
    private javax.swing.JScrollPane Listado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField TextoApellido;
    private javax.swing.JTextField TextoBusqueda;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoGrupo;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    // Método para actualizar la lista de contactos mostrada
    private void actualizarListaContactos(ArrayList<Contacto> contactosAMostrar) {
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        for (Contacto contacto : contactosAMostrar) {
            modeloLista.addElement(contacto.getNombre() + " " + contacto.getApellidos() + " - " + contacto.getTelefono());
        }
        ListaContactos.setModel(modeloLista);
        actualizarTotalContactos();
    }
    
    // Método para buscar contactos
    private void buscarContactos() {
        String criterioBusqueda = TextoBusqueda.getText().trim();
        if (criterioBusqueda.isEmpty()) {
            // Si no hay criterio de búsqueda, mostrar todos los contactos
            agenda.mostrarAgenda();
            actualizarListaContactos(agenda.buscarContactos(""));
        } else {
            ArrayList<Contacto> resultados = agenda.buscarContactos(criterioBusqueda);
            actualizarListaContactos(resultados);
            if (resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron contactos que coincidan con la búsqueda.");
            }
        }
    }
    
    // Método para actualizar el contador de contactos
    private void actualizarTotalContactos() {
        EtiquetaTotalContactos.setText("Total contactos: " + agenda.getTotalContactos());
    }
}
