/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joseg
 */
public class InterfazVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazVentanaPrincipa
     */
    private Agenda agenda;
    
    public InterfazVentanaPrincipal() {
        initComponents();
        agenda = new Agenda();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormulario = new javax.swing.JPanel();
        CampoNombre = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        CampoApellidos = new javax.swing.JLabel();
        TextoApellidos = new javax.swing.JTextField();
        CampoTeléfono = new javax.swing.JLabel();
        TextoTeléfono = new javax.swing.JTextField();
        CampoGrupo = new javax.swing.JLabel();
        TextoGrupo = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JLabel();
        TextoCorreo = new javax.swing.JTextField();
        AgregarContacto = new javax.swing.JButton();
        BotónLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoAreaContactos = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFormulario.setBackground(new java.awt.Color(247, 247, 247));
        panelFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelFormulario.setLayout(new java.awt.GridLayout(6, 0, 4, 3));

        CampoNombre.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        CampoNombre.setForeground(java.awt.Color.darkGray);
        CampoNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CampoNombre.setText("Nombre");
        CampoNombre.setName(""); // NOI18N
        panelFormulario.add(CampoNombre);

        TextoNombre.setBackground(java.awt.Color.white);
        TextoNombre.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        TextoNombre.setForeground(java.awt.Color.black);
        TextoNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoNombre.setToolTipText("Introduce Nombre");
        TextoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        TextoNombre.setMaximumSize(null);
        TextoNombre.setName(""); // NOI18N
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });
        panelFormulario.add(TextoNombre);

        CampoApellidos.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        CampoApellidos.setForeground(java.awt.Color.darkGray);
        CampoApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CampoApellidos.setText("Apellidos");
        CampoApellidos.setMaximumSize(new java.awt.Dimension(200, 200));
        CampoApellidos.setMinimumSize(new java.awt.Dimension(200, 200));
        CampoApellidos.setName(""); // NOI18N
        CampoApellidos.setPreferredSize(new java.awt.Dimension(200, 200));
        panelFormulario.add(CampoApellidos);

        TextoApellidos.setBackground(java.awt.Color.white);
        TextoApellidos.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        TextoApellidos.setForeground(java.awt.Color.black);
        TextoApellidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoApellidos.setToolTipText("Introduce Apellidos");
        TextoApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        TextoApellidos.setMaximumSize(null);
        TextoApellidos.setName(""); // NOI18N
        TextoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoApellidosActionPerformed(evt);
            }
        });
        panelFormulario.add(TextoApellidos);

        CampoTeléfono.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        CampoTeléfono.setForeground(java.awt.Color.darkGray);
        CampoTeléfono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CampoTeléfono.setText("Teléfono");
        CampoTeléfono.setName(""); // NOI18N
        panelFormulario.add(CampoTeléfono);

        TextoTeléfono.setBackground(java.awt.Color.white);
        TextoTeléfono.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        TextoTeléfono.setForeground(java.awt.Color.black);
        TextoTeléfono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoTeléfono.setToolTipText("Introduce nº de teléfono");
        TextoTeléfono.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        TextoTeléfono.setMaximumSize(null);
        TextoTeléfono.setName(""); // NOI18N
        panelFormulario.add(TextoTeléfono);

        CampoGrupo.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        CampoGrupo.setForeground(java.awt.Color.darkGray);
        CampoGrupo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CampoGrupo.setText("Grupo");
        CampoGrupo.setName(""); // NOI18N
        panelFormulario.add(CampoGrupo);

        TextoGrupo.setBackground(java.awt.Color.white);
        TextoGrupo.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        TextoGrupo.setForeground(java.awt.Color.black);
        TextoGrupo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoGrupo.setToolTipText("Introduce Grupo");
        TextoGrupo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        TextoGrupo.setMaximumSize(null);
        TextoGrupo.setName(""); // NOI18N
        panelFormulario.add(TextoGrupo);

        CampoCorreo.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        CampoCorreo.setForeground(java.awt.Color.darkGray);
        CampoCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CampoCorreo.setText("Correo");
        CampoCorreo.setName(""); // NOI18N
        panelFormulario.add(CampoCorreo);

        TextoCorreo.setBackground(java.awt.Color.white);
        TextoCorreo.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        TextoCorreo.setForeground(java.awt.Color.black);
        TextoCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextoCorreo.setToolTipText("Introduce correo electrónico");
        TextoCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        TextoCorreo.setMaximumSize(null);
        TextoCorreo.setName(""); // NOI18N
        panelFormulario.add(TextoCorreo);

        AgregarContacto.setBackground(new java.awt.Color(0, 168, 80));
        AgregarContacto.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        AgregarContacto.setForeground(java.awt.Color.white);
        AgregarContacto.setText("Agregar Contacto");
        AgregarContacto.setBorder(null);
        AgregarContacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarContacto.setPreferredSize(new java.awt.Dimension(101, 32));
        AgregarContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarContactoMouseClicked(evt);
            }
        });
        AgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarContactoActionPerformed(evt);
            }
        });
        panelFormulario.add(AgregarContacto);

        BotónLimpiar.setBackground(new java.awt.Color(0, 57, 188));
        BotónLimpiar.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        BotónLimpiar.setForeground(java.awt.Color.white);
        BotónLimpiar.setText("LIMPIAR CAMPOS");
        BotónLimpiar.setBorder(null);
        BotónLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotónLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónLimpiarMouseClicked(evt);
            }
        });
        BotónLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónLimpiarActionPerformed(evt);
            }
        });
        panelFormulario.add(BotónLimpiar);

        getContentPane().add(panelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 200));

        TextoAreaContactos.setBackground(new java.awt.Color(247, 247, 247));
        TextoAreaContactos.setColumns(20);
        TextoAreaContactos.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        TextoAreaContactos.setForeground(java.awt.Color.darkGray);
        TextoAreaContactos.setRows(5);
        TextoAreaContactos.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        TextoAreaContactos.setPreferredSize(new java.awt.Dimension(600, 200));
        jScrollPane1.setViewportView(TextoAreaContactos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, 600, 230));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 600, 40));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        getContentPane().add(jTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarContactoActionPerformed

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed

    private void AgregarContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarContactoMouseClicked
            // Obtener los datos de los campos
            String nombre = TextoNombre.getText();
            String apellido = TextoApellidos.getText();
            String telefono = TextoTeléfono.getText();
            String grupo = TextoGrupo.getText();
            String correo = TextoCorreo.getText();
            //Validar que el campo nombre no esté vacío ni apellido ni teléfono
            if (nombre.isEmpty() || telefono.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, rellene mínimo nombre y teléfono");return;}
            //Crear nuevo contacto y agregarlo
            Contacto nuevoContacto = new Contacto(nombre, apellido, telefono, grupo, correo);
            //Agregar a la agenda
            agenda.agregarContacto(nuevoContacto);
            //mostrar los contactos en el área de texto
            TextoAreaContactos.setText(TextoAreaContactos.getText()+"Nombre: " + nombre + " ");
            TextoAreaContactos.setText(TextoAreaContactos.getText()+"Apellidos: " + apellido + " ");
            TextoAreaContactos.setText(TextoAreaContactos.getText()+"Teléfono: " + telefono+ " ");
            TextoAreaContactos.setText(TextoAreaContactos.getText()+"Grupo: " + grupo+" " );
            TextoAreaContactos.setText(TextoAreaContactos.getText()+"Correo: " + correo+" " + "\n");
            TextoAreaContactos.setText(TextoAreaContactos.getText()+"-----------" + "\n");

       
            //Limpiar los campos
            TextoNombre.setText("");
            TextoApellidos.setText("");
            TextoTeléfono.setText("");
            TextoGrupo.setText("");
            TextoCorreo.setText("");
        
    }//GEN-LAST:event_AgregarContactoMouseClicked

    private void BotónLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotónLimpiarActionPerformed

    private void BotónLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónLimpiarMouseClicked
    TextoNombre.setText("");
    TextoApellidos.setText("");
    TextoTeléfono.setText("");
    TextoGrupo.setText("");
    TextoCorreo.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_BotónLimpiarMouseClicked

    private void TextoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoApellidosActionPerformed
// Método para mostrar los contactos en el área de texto
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new InterfazVentanaPrincipal().setVisible(true);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarContacto;
    private javax.swing.JButton BotónLimpiar;
    private javax.swing.JLabel CampoApellidos;
    private javax.swing.JLabel CampoCorreo;
    private javax.swing.JLabel CampoGrupo;
    private javax.swing.JLabel CampoNombre;
    private javax.swing.JLabel CampoTeléfono;
    private javax.swing.JTextField TextoApellidos;
    private javax.swing.JTextArea TextoAreaContactos;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoGrupo;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoTeléfono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelFormulario;
    // End of variables declaration//GEN-END:variables

}
